config:
  # this describes the inbox that we get emails from
  inbox:
    type: gmail  # gmail is the only implemented type
    user: 0xfe.254bot@gmail.com
    secret: INBOX_PASSWORD  # name of the GHA secret
    host: imap.gmail.com

  bot:
    token_name: BOT_TOKEN  # name of the GHA secret
    repo: 254bot/issues-repo
    # sendmail must be defined (really, need the name of the secret)
    # but unless emails-to-issue/reply-inbox is active, it won't be used
    sendmail:
      user: 0xfe.254bot@gmail.com
      secret: SENDMAIL_PASSWORD
      host: smtp.gmail.com

  team:
    # for each team member, give their GitHub username, enough of their
    # email addres that it is uniquely identifiable, and the Gmail label to
    # use when they've been assigned a task
    - github: dwhswenson
      email: david.swenson
      label: assigned/dwhswenson

workflows:
  # turn emails into GitHub issues
  emails-to-issues:
    active: true  # default True if listed
    dry: false  # default False
    cron: "0 */4 * * *"  # cron entry for when this should run
    filters:
      # filter out any emails written be the bot
      - name: bot
        active: true
      # filter out any from from team members unless inbox address is "To:"
      # Idea here is that CC/BCC to inbox should be filtered, but still
      # create an issue if a message if forwarded to the inbox by a team
      # member
      - name: team
        active: true
      # omit specific senders
      - name: omit-senders
        active: true
        senders:
          - notifications@github.com
    # only load emails more recent than this (rounded to the day); this
    # reduces download times when connecting to the inbox. Inputs are the
    # kwargs of datetime.timedelta
    recent:
      hours: 48
    # automatically send a reply to the inbox to say the 
    reply-inbox:
      active: true
      #template: reply.txt

  unassigned-reminder:
    active: true
    dry: false
    cron: "0 15 * * *"
    # only comment on issues that are recognized as created by 
    email-ticket-only: true
    delay:
      seconds: 1
    #template: ticgithub/data/templates/unassigned.txt
    notify:
      - dwhswenson

  unclosed-reminder:
    active: true
    dry: false
    cron: "0 15 * * *"
    email-ticket-only: true
    #template: ticgithub/data/templates/unclosed.txt
    delay:
      seconds: 1
    notify: []

  assignment-to-gmail:
    active: true
    dry: false
