config:
  # this describes the inbox that we get emails from
  inbox:
    type: gmail  # gmail is the only implemented type
    user: 0xfe.254bot@gmail.com
    #user: ticgithub@gmail.com
    secret: INBOX_PASSWORD  # this is the name
    host: imap.gmail.com

  bot:
    token_name: BOT_TOKEN
    repo: 254bot/issues-repo
    #repo: dwhswenson/ticgithub
    sendmail:
      user: 0xfe.254bot@gmail.com
      secret: SENDMAIL_PASSWORD
      host: smtp.google.com

  team:
    - github: dwhswenson
      email: david.swenson
      label: assigned/dwhswenson

workflows:
  emails-to-issues:
    active: true  # default True if listed
    dry: false  # default False
    cron: "0 */4 * * *"
    filters:
      - name: bot
        active: true
      - name: team
        active: true
    recent:
      hours: 48
    reply-inbox:
      active: true
      #template: reply.txt

  unassigned-reminder:
    active: true
    dry: false
    cron: "0 15 * * *"
    email-ticket-only: true
    delay:
      seconds: 1
    #template: ticgithub/data/templates/unassigned.txt
    notify:
      - dwhswenson

  unclosed-reminder:
    active: true
    dry: false
    cron: "0 15 * * *"
    email-ticket-only: true
    #template: ticgithub/data/templates/unclosed.txt
    delay:
      seconds: 1
    notify: []

  assignment-to-gmail:
    active: true
    dry: false
