name: assignment-to-gmail
on:
  issues:
    types: [assigned, unassigned]

jobs:
  assignment-to-gmail:
    runs-on: ubuntu-latest
    name: Add GMail Label
    steps:
      - uses: actions/checkout@v3
      - name: Install ticgithub
        run: python -m pip install ticgithub
      - name: Run ticgithub script
        run: python -m ticgithub.tasks.assignment_to_gmail  --loglevel INFO $ISSUE_NUM
        env: 
          ISSUE_NUM: ${{ github.event.issue.number }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          INBOX_PASSWORD: ${{ secrets.INBOX_PASSWORD }}
