name: emails-to-issues
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *

jobs:
  emails-to-issues:
    runs-on: ubuntu-latest
    name: emails-to-issues
    steps:
      - uses: actions/checkout@v3
      - name: Install ticgithub
        run: python -m pip install ticgithub
      - name: Run ticgithub script for emails-to-issues
        run: python -m ticgithub.tasks.emails_to_issues 
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          INBOX_PASSWORD: ${{ secrets.INBOX_PASSWORD }}
          SENDMAIL_PASSWORD: ${{ secrets.SENDMAIL_PASSWORD }}
