name: unassigned-reminder
on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * *

jobs:
  unassigned-reminder:
    runs-on: ubuntu-latest
    name: unassigned-reminder
    steps:
      - uses: actions/checkout@v3
      - name: Install ticgithub
        run: python -m pip install ticgithub
      - name: Run ticgithub script for unassigned-reminder
        run: python -m ticgithub.tasks.unassigned_reminder 
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          INBOX_PASSWORD: ${{ secrets.INBOX_PASSWORD }}
          SENDMAIL_PASSWORD: ${{ secrets.SENDMAIL_PASSWORD }}
