name: unclosed-reminder
on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * *

jobs:
  unclosed-reminder:
    runs-on: ubuntu-latest
    name: unclosed-reminder
    steps:
      - name: Install ticgithub
        run: python -m pip install ticgithub
      - name: Run ticgithub script for unclosed-reminder
        run: python -m ticgithub.tasks.unclosed_reminder 
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          INBOX_PASSWORD: ${{ secrets.INBOX_PASSWORD }}
          SENDMAIL_PASSWORD: ${{ secrets.SENDMAIL_PASSWORD }}
